require("plugins")
require("config")
require("telescopeconf")
require("treesitterconf")
require("completion")
require("gitconf")
require("formatting")
require("keys")
require("lspconf")
require("dapconf")
-- require("rust")
